# Generated by Django 6.0.5 on 2026-06-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('activity_level', models.FloatField(help_text='Multiplier: e.g. 1.2, 1.375, 1.55')),
                ('goal', models.CharField(choices=[('lose', 'Lose weight (-500 kcal)'), ('maintain', 'Maintain weight'), ('gain', 'Gain weight (+500 kcal)')], max_length=10)),
            ],
        ),
    ]
