# Generated by Django 6.0.5 on 2026-06-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='activity_level',
            field=models.FloatField(choices=[(1.2, 'Siedzący (brak ćwiczeń)'), (1.375, 'Niska aktywność (ćwiczenia 1-3x w tyg)'), (1.55, 'Średnia aktywność (ćwiczenia 3-5x w tyg)'), (1.725, 'Wysoka aktywność (ćwiczenia codziennie)'), (1.9, 'Bardzo wysoka (praca fizyczna)')]),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta')], max_length=1),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='goal',
            field=models.CharField(choices=[('lose', 'Odchudzanie (-500 kcal)'), ('maintain', 'Utrzymanie wagi'), ('gain', 'Budowa masy (+500 kcal)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='height',
            field=models.FloatField(help_text='Wzrost w cm'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='weight',
            field=models.FloatField(help_text='Waga w kg'),
        ),
    ]
